apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: auoj2oogm-go 
  janus-idp.io/tekton: auoj2oogm-go
  backstage.io/kubernetes-id: auoj2oogm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: auoj2oogm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  