apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: auoj2oogm-go
  janus-idp.io/tekton: auoj2oogm-go
  backstage.io/kubernetes-id: auoj2oogm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: auoj2oogm-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
